name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Sesuaikan dengan branch utama repositori

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build project
        run: |
          mkdir output
          cp -r src/* output/

      - name: Upload artifact (Gunakan v4)
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: output  # Pastikan sesuai dengan folder hasil build

      - name: Deploy to GitHub Pages (Gunakan v2)
        uses: actions/deploy-pages@v2
