name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Sesuaikan dengan branch utama

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build project
        run: |
          mkdir output
          cp -r src/* output/  # Sesuaikan dengan folder hasil build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2  # Sesuai versi terbaru
        with:
          name: github-pages  # Nama artifact harus konsisten
          path: output        # Path harus sesuai dengan hasil build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
